### ISSUE TITLE
Figma Responsiveness

### ISSUE THREAD

**Issue by tashwini-p** [tashwini-p/B32-Group5#16]
Tashwini's part:
- [x] Blue div 1
- [x] Yellow div 1
- [x] White div 1
- [x] Blue div 2 + Floating Yellow div 2
- [x] White div 2

Thakoor's part:
- [x] Blue div 3
- [x] White div 3
- [x] Blue div 4

Pratik's part:
- [x]  White div 4

Daya's part:
- [x] Yellow div 3
- [x] Blue div 5
- [x] Footer

**Comment by rishank07** [comment]
closed
